packaging_format = 2

id = "cjdns"
name = "Cjdns"

description.en = "Encrypted IPv6 network"
description.fr = "Réseau IPv6 chiffré"

version = "22.7~ynh1"

maintainers = ["dkoukoul"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/cjdelisle/cjdns/"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64","arm64"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
        [resources.sources.main]
        amd64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdroute_debian11_x86_64.tar.gz"
        amd64.sha256 = "32948ed786abd02d49c86ff614df5a49e629b14a7495ac96b641baddcd57945b"
        arm64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdroute_linux_arm64.tar.gz"
        arm64.sha256 = "8c391e024cc9094f0ec23ac325c2115013757da34fe730d46fc17436cf4773da"
        in_subdir = false
        
    [resources.system_user]
    
    [resources.install_dir]
    
    [resources.data_dir]

    [resources.ports]

    [resources.permissions]

    [resources.apt]
    packages = "curl, jq"
