packaging_format = 2

id = "cjdns"
name = "Cjdns"
description = "Cjdns encrypted IPv6 network"

version = "22.7"

maintainers = ["dkoukoul"]

[upstream]
license = "GPL-3.0"
website = "https://github.com/cjdelisle/cjdns/"
code = "https://github.com/cjdelisle/cjdns/"

[integration]
yunohost = ">= 11.1.21"
architectures = ["amd64","arm64"]
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
        [resources.sources.main]
        amd64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdroute_linux_x86_64.tar.gz"
        amd64.sha256 = "7385b98a3f7874a1fea14a6afeb9019d3595269b5c3282cb4dea35fc3b4a47ac"
        arm64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdroute_linux_arm64.tar.gz"
        arm64.sha256 = "8c391e024cc9094f0ec23ac325c2115013757da34fe730d46fc17436cf4773da"
    
    [resources.system_user]
    
    [resources.install_dir]
    
    [resources.data_dir]

    [resources.ports]

    [resources.permissions]

    [resources.apt]
    packages = "curl, nodejs, jq"
