packaging_format = 2

id = "cjdns"
name = "Cjdns"

description.en = "Encrypted IPv6 network"
description.fr = "Réseau IPv6 chiffré"

version = "22.7~ynh2"

maintainers = ["dkoukoul"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/cjdelisle/cjdns/"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64","arm64"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
        [resources.sources.main]
        amd64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdns_ynh_x86_64.tar.gz"
        amd64.sha256 = "8954e4fc894c9e0a1bea14ba27a44cf964bb2eb4ee18080470a3e1f3ed78dab7"
        arm64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdns_ynh_linux_arm64.tar.gz"
        arm64.sha256 = "e3b73bca6f282923967cefa96cf59d3258d06fec31779bfe90cac0a535a179d2"
        in_subdir = false
        
    [resources.system_user]
    
    [resources.install_dir]

    [resources.ports]

    [resources.permissions]

    [resources.apt]
    packages = "curl, jq"
